### ISSUE TITLE
request to support r.js empty paths

### ISSUE THREAD

**Issue by saunders99999** [pieterv/wire-rjs-builder#1]
Hi,

Thanks for thinking of the wire-rjs plug-in.  Very cool.  For optimizations, have you considered supporting the empty r.js config option.
http://requirejs.org/docs/optimization.html#empty

This would allow having AMD code references to external specs.  For instance, if spec1 is not in my code to be optimized... 

code

```
require( [ 'wire!spec1' ] );
```

r.js optimizer config

```
paths: {
        'spec1': 'empty:',
        'wire/builder/rjs': 'path/to/wire-rjs-builder/builder'
    },
```

could still be optimized.  This would be similar to how r.js can support CDN references to jquery, when it's not directly in the code base.

I tried this out, but kept getting things like missing '../../empty:' module when trying to optimize.

Thanks,
Mark

**Comment by pieterv** [comment]
Hey,

I would suggest instead of using the empty path config, package the wire spec as a module using the `exclude` config for removing it from the main package. See https://github.com/requirejs/example-multipage for an example of this.

Im not sure about your situation but if you don't do this the external wire spec will not get optimised and so once it has loaded all modules the spec requires will be loaded as separate resources as they will not be included in a built package. If this is not a problem for you then i would happily accept a pull request :)

**Comment by saunders99999** [comment]
Hi,

Sorry for the slow response, I was on vacation and had poor internet access.  I don't understand well the difference of exclude and empty.  I thought empty was more if you didn't have a module reference in your project, while exclude was for when having the reference, but would bundle it separately.  

In my case, I don't have the module reference.  Anyway, I'm getting pulled in a different direction and will see if later I can get some more review.  I'll have to try exclude again.  

For now, I'll close the topic and I have any additional info of interest, I'll bring this back up.

Thanks,
Mark
